# Generated by Django 4.2.4 on 2023-09-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetownership',
            name='notified_date',
            field=models.DateTimeField(null=True),
        ),
    ]
