# Generated by Django 4.2.4 on 2023-09-09 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets_monitoring', '0002_alter_assetownership_notified_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetownership',
            old_name='notified_date',
            new_name='notified_time',
        ),
    ]
